---
title: "Appendix"
author: "Kashaun Eghdam and Timothy Regis"
date: "10/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# The main focus of this code is to first, generate a sample frame of 1,000,000 responses to our survey, 
# next we take a sample of 5,000 of these responses which we will analyze. 
# In a series of Bar Graphs this code shows how our 5,000 respondent sample 
# would respond if actually given our survey.
```



```{r, results='hide'}
# Loading in Required Packages
library(tidyverse)
```

```{r, results='hide'}
#This code chunk is what designs our main survey dataset
set.seed(314)
pop <- 11796032
survey_size <- 1000000
my_data2 <- tibble(
# Simulation for question "What is your age".
  Age = sample(x = 
                 c("18 to 24", "25 to 34", "35 to 44", 
                 "45 to 54", "55 to 64", "65 to 74",
                   "75+", "Prefer not to say")
               ,size = survey_size,replace = TRUE,
               prob = c(0.11, 0.152, 0.15, 0.18, 0.165,
                           0.11, 0.112, 0.02)),
# Simulation for question "How likely are you to vote in the upcoming election?".
  Likelyhood_Vote =sample(x = c("Very likely", "Likely",
                     "Unlikely", "Very Unlikely",
                     "Don't Know/Prefer Not to answer"),
               size = survey_size, replace = TRUE,
               prob = c(0.375, 0.375, 0.115, 0.115, 0.02)),

# Simulation for question "How satisfied are you with the current operation of the Ontario government?".
  Current_Gov =sample(x = c("Very satisfied", "Satisfied",
                     "Neither satisfied nor dissatisfied", 
                     "Dissatisfied", "Very dissatisfied"),
               size = survey_size, replace = TRUE,
               prob = c(0.01, 0.25, 0.05, 0.35, 0.25)),

# Simulation for question "What is your opinion on the Minimum Wage rate in the Province?".
  Min_Wage =sample(x = c("Too high", "Just right",
                     "Too low", "Don't care/NA"),
               size = survey_size, replace = TRUE,
               prob = c(0.20, 0.23, 0.54, 0.03)),

# Simulation for question "In your opinion, taxes for those with an income".
# Income less than $40,000.
  Taxes_low =sample(x = c("Should be Higher","Should Stay about the Same",
                     "Should be Lower", "Don't Care/NA"),
                     size = survey_size, replace = TRUE, 
                     prob = c(0.07, 0.24, 0.65, 0.04)),
# Income between $40,000 and $200,000.
  Taxes_mid =sample(x = c("Should be Higher", "Should Stay about the Same",
                     "Should be Lower", "Don't Care/NA"),
                     size = survey_size, replace = TRUE,
                     prob = c(0.08, 0.32, 0.55, 0.05)),
#Income greater than $200,000.
  Taxes_high = sample(x = c("Should be Higher", "Should Stay about the Same",
                     "Should be Lower", "Don't Care/NA"),
                     size = survey_size, replace = TRUE,
                     prob = c(0.67, 0.2, 0.08, 0.05)),

# Simulation for question "On a scale from 1 to 5, how important do you think the preservation of Ontario's environment is?".
  Environment =sample(x = c(1:5),
               size = survey_size, replace = TRUE,
               prob = c(0.1, 0.1, 0.1, 0.3, 0.4)),

# Simulation for question "How much money would you like to see go toward benefiting those on welfare?".
  Welfare =sample(x = c("Spend More", "Spend less",
                           "Spend about the same as previous year",
                            "Don’t know/No Opinion"),
               size = survey_size, replace = TRUE,
               prob = c(0.3, 0.25, 0.4, 0.05)),

#Simulation for question "How much money should be spent on Healthcare facilities in Ontario?".
  Healthcare =sample(x = c("Spend More", "Spend less",
                           "Spend about the same as previous year",
                            "Don’t know/No Opinion"),
                     size = survey_size, replace = TRUE,
                     prob = c(0.78, 0.10, 0.10, 0.02)),

# Simulation for question "What do you think about the current price of hydroelectricity in Ontario?". 
 Hydro =sample(x = c("Too expensive", "Too cheap",
                           "Fairly priced", "No Opinion"),
                     size = survey_size, replace = TRUE,
                     prob = c(0.75, 0.08, 0.15, 0.02)),

# Simulation for question "Through what avenue do you most judge a political candidate?". 
  Gather_info =sample(x = c("Candidate address and speeches", "Online news sources",
                        "TV", "Newspaper articles", "Social Media", "Other"),
                     size = survey_size, replace = TRUE,
                     prob = c(0.1, 0.25, 0.36, 0.5, 0.37, 0.03)),
)
```

```{r, fig.cap = 'Table 1', results='hide'}
set.seed(314)
my_data <- sample_n(my_data2, 10000)
head(my_data)
```

```{r,fig.cap = 'Figure 1' ,results='hide',warning=FALSE}
# Bar Graph for question "How satisfied are you with the current operation of the Ontario government?"
my_data %>%
  ggplot(aes(x = Current_Gov)) + 
  geom_bar(color = 'black', fill = 'Green') + 
  labs(title = "Voters' Satisfaction with Current Government", 
       x = "Level of Satisfaction", 
       y = "Number of Responses",
       caption = "Figure 1 - Source: Simulated dataset.") + 
  theme_minimal() + 
  geom_text(stat='count', aes(label=..count..), vjust=-1) + theme(axis.text.x=element_text(angle=45,hjust=1))
```

```{r, fig.cap="Figure 2",results='hide',warning=FALSE}
#Bar graph for question "What is your opinion on the Minimum Wage rate in the Province"
my_data %>%
  ggplot(aes(x = Min_Wage)) + 
  geom_bar(color = 'black',fill = "yellow") + labs(title="Voter Opinions on the Current Level of Minimum Wage",
       x = "Opinion on current Minimum Wage",
       y = "Number of Responses",
       caption = "Figure 2 - Source: Simulated dataset.") +
  theme_minimal()
```

```{r, fig.cap="Figure 3.1",results='hide',warning=FALSE}
# Bar plot for question "In your opinion, taxes for those with an income:Less than $40,000"
my_data %>%
  ggplot(aes(x = Taxes_low)) + 
  geom_bar(color = 'black',fill = "orange") + 
  labs(title="Income Tax Rate Reccomendation for 
       Annual Income under $40,000 by Voters",
       x = "Reccomendation on Tax Rate",
       y = "Number of responses",
       caption = "Figure 3.1 - Source: Simulated dataset.") +
  theme_minimal()
```
```{r, fig.cap="Figure 3.2",results='hide',warning=FALSE}
#Bar plot for question "In your opinion, taxes for those with an income:Between $40,000 and $200,000"
my_data %>%
  ggplot(aes(x =Taxes_mid )) + 
  geom_bar(color = 'black',fill = "orange") +
  labs(title="Income Tax Rate Reccomendation for 
       Annual Income between $40,000 and $200,000 by Voters",
       x = "Reccomendation on Tax Rate",
       y = "Number of responses",
       caption = "Figure 3.2 - Source: Simulated dataset.") +
  theme_minimal()
```
```{r, fig.cap="Figure 3.3",results='hide',warning=FALSE}
# Bar plot for question"In your opinion, taxes for those with an income:Greater than $200,000"
my_data %>%
  ggplot(aes(x = Taxes_high )) + 
  geom_bar(color = 'black',fill = "orange") + 
  labs(title="Income Tax Rate Reccomendation for 
       Annual Income over $200,000 by Voters",
        x = "Reccomendation on Tax Rate",
        y = "Number of responses",
        caption = "Figure 3.3 - Source: Simulated dataset.") +
  theme_minimal()
```

```{r,fig.cap='Figure 4',results='hide', warning=FALSE}
#Bar plot for question "How much money should be spent on Healthcare in Ontario?"
my_data %>%
  ggplot(aes(x = Healthcare)) + 
  geom_bar(color = 'black',fill = "steelblue") +
  labs(title="Healthcare Spending Reccomendation by voters",
         x = "Spending Reccomendation", 
         y = "Number of responses",
         caption = "Figure 4 - Source: Simulated dataset.") + 
  theme_minimal()
```

```{r,fig.cap='Figure 5',results='hide',warning=FALSE}
# Bar plot for question "How much money would you like to see go toward benefiting those on welfare"
my_data %>%
  ggplot(aes(x = Welfare)) + 
  geom_bar(color = 'black',fill = "steelblue") + 
  labs(title="Welfare Spending Reccomendations by Voters",
       x = "Spending Reccomendation",
       y = "Number of responses",
       caption = "Figure 5 - Source: Simulated dataset.") +
  theme_minimal()
```

```{r,fig.cap='Figure 6',results='hide',warning=FALSE}
# Bar plot for question "On a scale from 1 to 5, how important do you think the preservation of Ontario's environment is?"
my_data %>%
  ggplot(aes(x = Environment)) + 
  geom_bar(color = 'black',fill = "steelblue") + 
  labs(title="Importantance of Protecting the Environment to Voters",
       x = "Level of Importance",
       y = "Number of responses",
       caption = "1 = Not Important, 5 = Very Important.                 Figure 6 - Source: Simulated dataset.") +
  theme_minimal()
```

```{r,fig.cap='Figure 7',results='hide',warning=FALSE}
# Bar plot for the question "What do you think about the current cost of hydroelectricity?"
my_data %>%
  ggplot(aes(x = Hydro)) + 
  geom_bar(color = 'black',fill = "firebrick1") + 
  labs(title="Opinions on current Hydroelectricity Prices in Ontario",
       x = "Opinion",
       y = "Number of responses",
       caption = "Figure 7 - Source: Simulated dataset.") +
  theme_minimal()
```

```{r, fig.cap='Figure 8',results='hide',warning=FALSE}
#Bar plot for the question "Through what avenue do you most judge a political candidate?"
my_data %>%
  ggplot(aes(x = Gather_info)) + 
  geom_bar(color = 'black',fill = "deepskyblue") + 
  labs(title="Oulets that voters use most to judge a candidate",
       x = "Media Outlets",
       y = "Number of responses",
       caption = "Figure 8 - Source: Simulated dataset.") + 
  theme_minimal()
```
